# Generated by Django 3.0.3 on 2020-03-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200304_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='i.jpg', upload_to=''),
        ),
    ]
