# Generated by Django 3.0.4 on 2020-03-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200305_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_department_head',
            field=models.BooleanField(default=False, verbose_name='head status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_general_manager',
            field=models.BooleanField(default=False, verbose_name='GM status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='owner status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_supplier',
            field=models.BooleanField(default=False, verbose_name='supplier status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
