# Generated by Django 3.0.4 on 2020-03-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200309_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_department_head',
            field=models.BooleanField(default=False, verbose_name='Head of department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_general_manager',
            field=models.BooleanField(default=False, verbose_name='General Manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='owner '),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Normal Staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_supplier',
            field=models.BooleanField(default=False, verbose_name='supplier '),
        ),
    ]
