# Generated by Django 3.0.3 on 2020-02-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AddField(
            model_name='products',
            name='ABC_category',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='FSN_analysis',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='VED_analysis',
            field=models.CharField(choices=[('Vital', 'Vital'), ('Essential', 'Essential'), ('Desirable', 'Desirable')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='buy_or_make',
            field=models.CharField(choices=[('make', 'Make'), ('buy', 'Buy')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='item_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='safety_stock_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='unit_measure',
            field=models.CharField(choices=[('Kilograms', 'Kilograms'), ('Liters', 'Liters'), ('Meters', 'Meters'), ('Piece', 'Piece'), ('Tonne', 'Tonne')], max_length=20),
        ),
    ]
