# Generated by Django 3.0.3 on 2020-02-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200227_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
