# Generated by Django 3.0.3 on 2020-03-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='date_delivery',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='date_expiry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='date_finished',
            field=models.DateField(),
        ),
    ]
