# Generated by Django 3.0.3 on 2020-03-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200305_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='date_delivery',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
