# Generated by Django 3.0.3 on 2020-02-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderapplication',
            name='discount_terms',
            field=models.TextField(default='nill'),
        ),
    ]
