# Generated by Django 3.0.3 on 2020-02-28 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='rating',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tenderapplication',
            name='tender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tender', to='supplier.Tender'),
        ),
        migrations.AlterField(
            model_name='tenderapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL),
        ),
    ]
